// <auto-generated />
using System;
using ELEKTRA.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ELEKTRA.DataAccess.Migrations
{
    [DbContext(typeof(ElektraContext))]
    [Migration("20250315115009_AddCreatedAtField")]
    partial class AddCreatedAtField
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ELEKTRA.DataAccess.Entities.Calculation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<double>("DailyCost")
                        .HasColumnType("float");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ElectricityCost")
                        .HasColumnType("float");

                    b.Property<double>("HourlyCost")
                        .HasColumnType("float");

                    b.Property<double>("Kilowatts")
                        .HasColumnType("float");

                    b.Property<double>("MonthlyCost")
                        .HasColumnType("float");

                    b.Property<double>("Watts")
                        .HasColumnType("float");

                    b.Property<double>("WeeklyCost")
                        .HasColumnType("float");

                    b.Property<double>("YearlyCost")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Calculations");
                });
#pragma warning restore 612, 618
        }
    }
}
